//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18408
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Livet.Design.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Livet.Design.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   確認ダイアログを表示するアクションです。ConfirmMessage(戻り値あり)に対応します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmDialogInteractionMessageAction_Description {
            get {
                return ResourceManager.GetString("ConfirmDialogInteractionMessageAction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示するメッセージボックスボタンの形式を指定します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmMessage_Button_Description {
            get {
                return ResourceManager.GetString("ConfirmMessage_Button_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャプションです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmMessage_Caption_Description {
            get {
                return ResourceManager.GetString("ConfirmMessage_Caption_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確認相互作用メッセージです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmMessage_Description {
            get {
                return ResourceManager.GetString("ConfirmMessage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メッセージボックスイメージです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmMessage_Image_Description {
            get {
                return ResourceManager.GetString("ConfirmMessage_Image_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示するメッセージです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmMessage_Text_Description {
            get {
                return ResourceManager.GetString("ConfirmMessage_Text_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前が表すコントロールのバインドできないプロパティへ、指定されたソースから値を反映するためのビヘイビアです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlBindingSupport_OneWayToControl_Description {
            get {
                return ResourceManager.GetString("ControlBindingSupport_OneWayToControl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アタッチされたコントロールのバインドできないプロパティのうち、このビヘイビアを使用してソースから値を反映したいプロパティを表します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlBindingSupport_OneWayToControl_Property_Description {
            get {
                return ResourceManager.GetString("ControlBindingSupport_OneWayToControl_Property_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このビヘイビアを使用して値をコントロールのプロパティに反映するためのソースを表します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlBindingSupport_OneWayToControl_Source_Description {
            get {
                return ResourceManager.GetString("ControlBindingSupport_OneWayToControl_Source_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前が表すコントロールのバインドできないプロパティから、指定されたソースへ値を反映するためのアクションです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlBindingSupport_OneWayToSource_Description {
            get {
                return ResourceManager.GetString("ControlBindingSupport_OneWayToSource_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アタッチされたコントロールのバインドできないプロパティのうち、このアクションを使用してソースへ値を反映したいプロパティを表します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlBindingSupport_OneWayToSource_Property_Description {
            get {
                return ResourceManager.GetString("ControlBindingSupport_OneWayToSource_Property_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このアクションを使用して値を反映したいソースを表します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlBindingSupport_OneWayToSource_Source_Description {
            get {
                return ResourceManager.GetString("ControlBindingSupport_OneWayToSource_Source_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アタッチしたオブジェクトのDataContextがIDisposableである場合、Disposeします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DataContextDisposeAction_Description {
            get {
                return ResourceManager.GetString("DataContextDisposeAction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アクション実行後に実行するコマンドです。このプロパティが設定されていた場合、アクションの実行後アクションの実行に使用した相互作用メッセージをパラメータとして指定されたコマンドを呼び出します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DirectInteractionMessage_CallbackCommand_Description {
            get {
                return ResourceManager.GetString("DirectInteractionMessage_CallbackCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アクション実行後に呼び出すメソッドの名前です。このプロパティとCallbackMethodTargetが設定されていた場合、アクションの実行後アクションの実行に使用した相互作用メッセージをパラメータとして指定されたメソッドを呼び出します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DirectInteractionMessage_CallbackMethodName_Description {
            get {
                return ResourceManager.GetString("DirectInteractionMessage_CallbackMethodName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アクション実行後に呼び出すメソッドを持つオブジェクトです。このプロパティとCallbackMethodNameが設定されていた場合、アクションの実行後アクションの実行に使用した相互作用メッセージをパラメータとしてメソッドを呼び出します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DirectInteractionMessage_CallbackMethodTarget_Description {
            get {
                return ResourceManager.GetString("DirectInteractionMessage_CallbackMethodTarget_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Viewから直接相互作用メッセージを定義する際に使用します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DirectInteractionMessage_Description {
            get {
                return ResourceManager.GetString("DirectInteractionMessage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   相互作用メッセージ(各種InteractionMessage)です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DirectInteractionMessage_Message_Description {
            get {
                return ResourceManager.GetString("DirectInteractionMessage_Message_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   拡張子を指定しなかった場合、自動で拡張子を追加するかどうかです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileSelectionMessage_AddExtension_Description {
            get {
                return ResourceManager.GetString("FileSelectionMessage_AddExtension_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルの拡張子Filterです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileSelectionMessage_Filter_Description {
            get {
                return ResourceManager.GetString("FileSelectionMessage_Filter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ダイアログに表示される初期ディレクトリです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileSelectionMessage_InitialDirectory_Description {
            get {
                return ResourceManager.GetString("FileSelectionMessage_InitialDirectory_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ダイアログタイトルです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileSelectionMessage_Title_Description {
            get {
                return ResourceManager.GetString("FileSelectionMessage_Title_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   情報ダイアログを表示するアクションです。InformationMessageに対応します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InformationDialogInteractionMessageAction_Description {
            get {
                return ResourceManager.GetString("InformationDialogInteractionMessageAction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャプションです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InformationMessage_Caption_Description {
            get {
                return ResourceManager.GetString("InformationMessage_Caption_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   情報をViewに通知するためのメッセージです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InformationMessage_Description {
            get {
                return ResourceManager.GetString("InformationMessage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メッセージボックスイメージです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InformationMessage_Image_Description {
            get {
                return ResourceManager.GetString("InformationMessage_Image_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示するメッセージです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InformationMessage_Text_Description {
            get {
                return ResourceManager.GetString("InformationMessage_Text_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   相互作用メッセージの基底クラスです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InteractionMessage_Description {
            get {
                return ResourceManager.GetString("InteractionMessage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Windowがアクティブな時のみアクションを実行するかどうかです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InteractionMessageAction_InvokeActionOnlyWhenWindowIsActive_Description {
            get {
                return ResourceManager.GetString("InteractionMessageAction_InvokeActionOnlyWhenWindowIsActive_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ViewModelからの相互作用メッセージを受信し、アクションを実行します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InteractionMessageTrigger_Description {
            get {
                return ResourceManager.GetString("InteractionMessageTrigger_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このトリガーが発火するのをアタッチされたオブジェクトがロードされている期間(Loaded~Unloaded)だけにするかどうかを表します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InteractionMessageTrigger_InvokeActionsOnlyWhileAttatchedObjectLoaded_Description {
            get {
                return ResourceManager.GetString("InteractionMessageTrigger_InvokeActionsOnlyWhileAttatchedObjectLoaded_Description" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このトリガーが有効かどうかを表します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InteractionMessageTrigger_IsEnable_Description {
            get {
                return ResourceManager.GetString("InteractionMessageTrigger_IsEnable_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このトリガーが反応する相互作用メッセージのメッセージキーをです。このプロパティが指定されていない場合、このトリガーは全ての相互作用メッセージに反応します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InteractionMessageTrigger_MessageKey_Description {
            get {
                return ResourceManager.GetString("InteractionMessageTrigger_MessageKey_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画面遷移(Window)を行うアクションです。TransitionMessageに対応します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InteractionTransitionAction_Description {
            get {
                return ResourceManager.GetString("InteractionTransitionAction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ターゲットオブジェクトでメソッドを呼び出しします。BlendSDKのCallMethodActionと異なる点として、引数が１つのメソッドまで呼び出す事が可能です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LivetCallMethodAction_Description {
            get {
                return ResourceManager.GetString("LivetCallMethodAction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DataTriggerです。BlendSDKのDataTriggerと異なる店として、初期値に対応しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LivetDataTrigger_Description {
            get {
                return ResourceManager.GetString("LivetDataTrigger_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   「ファイルを開く」ダイアログを表示するアクションです。SelectOpenFileMessage(戻り値有)に対応します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpenFileDialogInteractionMessageAction_Description {
            get {
                return ResourceManager.GetString("OpenFileDialogInteractionMessageAction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルを開く アクション用の相互作用メッセージです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpeningFileSelectionMessage_Description {
            get {
                return ResourceManager.GetString("OpeningFileSelectionMessage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   複数ファイルを選択可能かどうかです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpeningFileSelectionMessage_MultiSelect_Description {
            get {
                return ResourceManager.GetString("OpeningFileSelectionMessage_MultiSelect_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PasswordBoxのPasswordをバインド可能にするためのビヘイビア に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PasswordBoxBindingSupportBehavior_Description {
            get {
                return ResourceManager.GetString("PasswordBoxBindingSupportBehavior_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アタッチされたPasswordBoxのバインド可能なPasswordプロパティ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PasswordBoxBindingSupportBehavior_Password_Description {
            get {
                return ResourceManager.GetString("PasswordBoxBindingSupportBehavior_Password_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   戻り値のある相互作用メッセージの基底クラスです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ResponsiveInteractionMessage_Description {
            get {
                return ResourceManager.GetString("ResponsiveInteractionMessage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RoutedEventのためのEventTriggerです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RoutedEventTrigger_Description {
            get {
                return ResourceManager.GetString("RoutedEventTrigger_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   「ファイルを保存する」ダイアログを表示するアクションです。SelectSaveFileMessage(戻り値有)に対応します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveFileDialogInteractionMessageAction_Description {
            get {
                return ResourceManager.GetString("SaveFileDialogInteractionMessageAction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーが存在しないファイルを指定した場合に、ファイルを作成することを確認するメッセージを表示するかどうかです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SavingFileSelectionMessage_CreatePrompt_Description {
            get {
                return ResourceManager.GetString("SavingFileSelectionMessage_CreatePrompt_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルを保存する 用の相互作用メッセージです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SavingFileSelectionMessage_Description {
            get {
                return ResourceManager.GetString("SavingFileSelectionMessage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーが指定したファイルが存在する場合、上書き確認メッセージを表示するかどうかです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SavingFileSelectionMessage_OverwritePrompt_Description {
            get {
                return ResourceManager.GetString("SavingFileSelectionMessage_OverwritePrompt_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アタッチしているコントロールにフォーカスを試みます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SetFocusAction_Description {
            get {
                return ResourceManager.GetString("SetFocusAction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TextBoxの選択文字列に関わるプロパティをバインド可能にするためのビヘイビア に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextBoxBindingSupportBehavior_Description {
            get {
                return ResourceManager.GetString("TextBoxBindingSupportBehavior_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アタッチされたTextBoxのバインド可能なSelectionLengthプロパティ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextBoxBindingSupportBehavior_SelectedLength_Description {
            get {
                return ResourceManager.GetString("TextBoxBindingSupportBehavior_SelectedLength_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アタッチされたTextBoxのバインド可能なSelectedStartプロパティ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextBoxBindingSupportBehavior_SelectedStart_Description {
            get {
                return ResourceManager.GetString("TextBoxBindingSupportBehavior_SelectedStart_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アタッチされたTextBoxのバインド可能なSelectedTextプロパティ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextBoxBindingSupportBehavior_SelectedText_Description {
            get {
                return ResourceManager.GetString("TextBoxBindingSupportBehavior_SelectedText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Livet/バインディングサポート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolBoxCategory_ControlBindingSupport {
            get {
                return ResourceManager.GetString("ToolBoxCategory_ControlBindingSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Livet/バインディングサポート/コントロールへの単方向ビヘイビア に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolBoxCategory_ControlBindingSupport_OneWayToControl {
            get {
                return ResourceManager.GetString("ToolBoxCategory_ControlBindingSupport_OneWayToControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Livet/バインディングサポート/ソースへの単方向アクション に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolBoxCategory_ControlBindingSupport_OneWayToSource {
            get {
                return ResourceManager.GetString("ToolBoxCategory_ControlBindingSupport_OneWayToSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Livet/メッセージング に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolBoxCategory_Messaging {
            get {
                return ResourceManager.GetString("ToolBoxCategory_Messaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Livet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolBoxCategory_Root {
            get {
                return ResourceManager.GetString("ToolBoxCategory_Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   遷移先WindowがこのWindowに所有されるかどうかを表します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TransitionInteractionMessageAction_IsOwned_Description {
            get {
                return ResourceManager.GetString("TransitionInteractionMessageAction_IsOwned_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画面遷移の種類を表します。TransitionMessageでModeがUnKnown以外に指定されていた場合、そちらが優先されます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TransitionInteractionMessageAction_Mode_Description {
            get {
                return ResourceManager.GetString("TransitionInteractionMessageAction_Mode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   遷移先のWindowの型です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TransitionInteractionMessageAction_WindowType_Description {
            get {
                return ResourceManager.GetString("TransitionInteractionMessageAction_WindowType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画面遷移アクション用の相互作用メッセージです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TransitionMessage_Description {
            get {
                return ResourceManager.GetString("TransitionMessage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新しいWindowの表示方法を決定します。InteractionTransitionActionで指定されたものより優先されます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TransitionMessage_Mode_Description {
            get {
                return ResourceManager.GetString("TransitionMessage_Mode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   遷移先WindowのDataContextに設定するViewModelです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TransitionMessage_TransitionViewModel_Description {
            get {
                return ResourceManager.GetString("TransitionMessage_TransitionViewModel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Windowが遷移すべき状態です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WindowActionMessage_Action_Description {
            get {
                return ResourceManager.GetString("WindowActionMessage_Action_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Windowを最大化・最小化・閉じる・通常化させるための相互作用メッセージです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WindowActionMessage_Description {
            get {
                return ResourceManager.GetString("WindowActionMessage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WindowのCloseをキャンセル後に実行するコマンドです。このプロパティが設定されていた場合、WindowのCloseをキャンセル後に指定されたコマンドを実行します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WindowCloseCancelBehavior_CallbackCommand_Description {
            get {
                return ResourceManager.GetString("WindowCloseCancelBehavior_CallbackCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WindowのCloseをキャンセル後に実行するメソッドの名前です。このプロパティとCallBackMethodTargetが設定されていた場合、WindowのCloseをキャンセル後に指定されたメソッドを呼び出します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WindowCloseCancelBehavior_CallbackMethodName_Description {
            get {
                return ResourceManager.GetString("WindowCloseCancelBehavior_CallbackMethodName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WindowのCloseをキャンセル後に実行するメソッドを持つオブジェクトです。このプロパティとCallBackMethodNameが設定されていた場合、WindowのCloseをキャンセル後に指定されたメソッドを呼び出します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WindowCloseCancelBehavior_CallbackMethodTarget_Description {
            get {
                return ResourceManager.GetString("WindowCloseCancelBehavior_CallbackMethodTarget_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アタッチしたWindowをCloseできるかどうかです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WindowCloseCancelBehavior_CanClose_Description {
            get {
                return ResourceManager.GetString("WindowCloseCancelBehavior_CanClose_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WindowのClose処理をキャンセルし、キャンセルした事をCallback通知可能なビヘイビア に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WindowCloseCancelBehavior_Description {
            get {
                return ResourceManager.GetString("WindowCloseCancelBehavior_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Windowの最小化・最大化・閉じるを行うアクションです。WindowActionMessageに対応します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WindowInteractionMessageAction_Description {
            get {
                return ResourceManager.GetString("WindowInteractionMessageAction_Description", resourceCulture);
            }
        }
    }
}
